# config.yaml
# Configuration file for the system
# Can choose logs folder, log details activation, enabled actuators, buffering parameters
#
# Author: Stefano Concas
# Github: https://github.com/steconcas15
# Repository: https://github.com/steconcas15/PROJECT_CPSA_2026
# License: MIT

# ---- LOGS & DEBUG CONFIGURATION ----
log_base_path: ~/Desktop/CPSA_logs  # Path where logs are saved. User folder is automatically detected

enable_system_log: true      # Create/Log system status messages
enable_actuation_detail: false  # Log actuation used for that event

debug_system_console: true   # Choose to print system events on the console
debug_event_console: true    # Choose to print events on the console

# ---- DPU MODELS PATHS ----
yolo_model_name: "/home/ubuntu/Desktop/PROJECT_CPSA_2026/Video_Pipeline/Yolo_v3u/kv260_train_yolo_v3.xmodel"
resnet_model_name: "/home/ubuntu/Desktop/PROJECT_CPSA_2026/Video_Pipeline/Resnet18/kv260_train_resnet18_drowsy.xmodel"

# ---- SENSORS AND ACTUATORS CONFIGS ----
bluecoins:
  - id: bc_left
    name: "CPSA_L2"
  - id: bc_right
    name: "CPSA_R2"

metamotion:
  enable: true                # Device activation flag
  scan_timeout: 2             # First scan duration in seconds
  fast_retry_attempts: 5      # Number of fast retries after a disconnection
  retry_interval: 5           # Wait time between fast retries
  retry_sleep: 60             # Wait time between subsequent retries

speaker:
  mac: D4:8C:49:C9:DC:9A      # Device MAC address
  enable: false                # Device activation flag
  scan_timeout: 5             # First scan duration in seconds
  fast_retry_attempts: 5      # Number of fast retries after a disconnection
  retry_interval: 10          # Wait time between fast retries
  retry_sleep: 60             # Wait time between subsequent retries
